name = "HighlyAdaptiveLasso"
uuid = "c5dac772-1445-43c4-b698-9440de7877f6"
authors = ["Olivier Labayle"]
version = "0.1.0"

[deps]
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
MLJModelInterface = "1"
RCall = "0.13"
julia = "1"
